### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by DotTheI** [danielbuechele/goofy#119]
Suddenly, a while after the last update, resizing window to a minimum width results in this:

![2015-07-21 12 35 55](https://cloud.githubusercontent.com/assets/10737439/8801287/22376216-2fc2-11e5-9a1f-f7852299b65a.png)

**Comment by danielbuechele** [comment]
fixed

**Comment by DotTheI** [comment]
Not really fixed
![2015-08-07 11 15 58](https://cloud.githubusercontent.com/assets/10737439/9131605/c60062f4-3cf5-11e5-8509-26b0292c4aab.png)

**Comment by DotTheI** [comment]
Also, don't know why, but the font size doesn't become smaller, even after downgrading to 2.1.2.

**Comment by danielbuechele** [comment]
fixed

**Comment by DotTheI** [comment]
Daniel, please advise, why the font of the message no longer becomes smaller as the window size is made smaller?
